spring:
  application:
    name: opsdesk

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/opsdesk}
    username: ${SPRING_DATASOURCE_USERNAME:opsdesk}
    password: ${SPRING_DATASOURCE_PASSWORD:opsdesk}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

opsdesk:
  demo-data:
    enabled: ${OPS_DESK_DEMO_DATA_ENABLED:false}
  security:
    jwt:
      secret: ${OPS_DESK_JWT_SECRET:dev-only-change-this-jwt-secret-for-opsdesk}
      expiration: PT2H
